In [211]:
import pandas as pd
import numpy as np

In [212]:
df = pd.read_csv("netflix_titles.csv")

In [213]:
print(df.head())
print(df.info())
print(df.describe())
print(df.shape)

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water              NaN
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans              NaN
4      s5  TV Show           Kota Factory              NaN

                                                cast        country  \
0                                                NaN  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                NaN            NaN
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

           date_added  release_year rating   duration  \
0  September 25, 2021          2020  PG-13     90 min
1  September 24, 2021          2021  TV-MA  2 Seasons
2  September 24, 2021          2021  TV-MA   1 Season
3  September 24, 2021          2021  TV-MA   1 Season
4  September 24, 2021          2021  TV-MA  2 Seasons

                                           listed_in  \
0                                      Documentaries
1    International TV Shows, TV Dramas, TV Mysteries
2  Crime TV Shows, International TV Shows, TV Act...
3                             Docuseries, Reality TV
4  International TV Shows, Romantic TV Shows, TV ...

                                         description
0  As her father nears the end of his life, filmm...
1  After crossing paths at a party, a Cape Town t...
2  To protect his family from a powerful drug lor...
3  Feuds, flirtations and toilet talk go down amo...
4  In a city of coaching centers known to train I...
<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB
None
       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000
(8807, 12)

In [214]:
print(df.dtypes)

show_id           str
type              str
title             str
director          str
cast              str
country           str
date_added        str
release_year    int64
rating            str
duration          str
listed_in         str
description       str
dtype: object

In [215]:
print(df.isnull().sum())

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [216]:
missing = df.isnull().sum() / len(df) * 100
print(missing.sort_values(ascending=False))

director        29.908028
country          9.435676
cast             9.367549
date_added       0.113546
rating           0.045418
duration         0.034064
show_id          0.000000
type             0.000000
title            0.000000
release_year     0.000000
listed_in        0.000000
description      0.000000
dtype: float64

In [217]:
print(df.duplicated().sum())

df.drop_duplicates(inplace=True)

0

In [218]:
df["director"] = df["director"].fillna("Unknown")

In [219]:
df["country"] = df["country"].fillna("Unknown")

In [220]:
df.dropna(subset=["date_added"], inplace=True)

In [221]:
print(df["date_added"].dtype)

str

In [222]:
df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")

C:\Users\julia\AppData\Local\Temp\ipykernel_7628\2959040179.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")

In [223]:
df["date_added"].isna().sum()

np.int64(0)

In [224]:
df[df["date_added"].isna()]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [225]:
df["date_added"] = pd.to_datetime(
    df["date_added"].astype(str).str.strip(),
    errors="coerce"
)

In [226]:
print(df["date_added"].dtype)

datetime64[us]

In [227]:
df["date_added"].isna().sum() / len(df) * 100

np.float64(0.0)

In [228]:
missing_count = df["date_added"].isna().sum()
missing_percent = missing_count / len(df) * 100

print("Brakujące daty:", missing_count)
print("Procent braków:", round(missing_percent, 2), "%")

Brakujące daty: 0
Procent braków: 0.0 %

In [229]:
df[df["date_added"].isna()]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [230]:
df.loc[df["date_added"].isna(), "date_added"]

Series([], Name: date_added, dtype: datetime64[us])

In [231]:
df["date_added_raw"] = df["date_added"]

df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")

df[df["date_added"].isna()][["date_added_raw"]]

Empty DataFrame
Columns: [date_added_raw]
Index: []

In [232]:
print("Analiza date_added zakończona – brakujące wartości pozostawiono bez imputacji")

Analiza date_added zakończona – brakujące wartości pozostawiono bez imputacji

Analiza i czyszczenie kolumny 'cast'

In [233]:
print("Brakujące wartości w kolumnie cast:")
print(df["cast"].isnull().sum())

Brakujące wartości w kolumnie cast:
825

In [234]:
df.loc[df["cast"].isna(), ["title", "director", "cast"]]

,title,director,cast
0,Dick Johnson Is Dead,Kirsten Johnson,NaN
3,Jailbirds New Orleans,Unknown,NaN
10,"Vendetta: Truth, Lies and The Mafia",Unknown,NaN
14,Crime Stories: India Detectives,Unknown,NaN
16,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN
...,...,...,...
8746,Winnie,Pascale Lamche,NaN
8755,Women Behind Bars,Unknown,NaN
8756,Woodstock,Barak Goodman,NaN
8763,WWII: Report from the Aleutians,John Huston,NaN
8803,Zombie Dumb,Unknown,NaN

In [235]:
df["cast"] = df["cast"].fillna("Unknown")

In [236]:
print(df["cast"].isnull().sum())

0

Sprawdzenie czy w kolumnie Title nie ma typu: film albo serial

In [238]:
df[df["title"].isin(["Movie", "TV Show"])]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description, date_added_raw]
Index: []

sprawdzenie długości tytułów

In [239]:
df[df["title"].str.len() < 3]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,date_added_raw
2069,s2070,TV Show,H,Unknown,"Jamel Debbouze, Éric Judor, Ramzy Bedia, Cathe...",France,2020-09-01,2002,TV-MA,4 Seasons,"International TV Shows, TV Comedies","At a dysfunctional hospital in Paris, three bu...",2020-09-01
2127,s2128,TV Show,3%,Unknown,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,2020-08-14,2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...,2020-08-14
3668,s3669,Movie,4L,Gerardo Olivares,"Jean Reno, Hovik Keuchkerian, Susana Abaitua, ...",Spain,2019-07-12,2019,TV-MA,105 min,"Comedies, Dramas, Independent Movies","Hoping to reunite with a dying friend, two lon...",2019-07-12
4090,s4091,TV Show,Z4,Unknown,"Apollo Costa, Gabriel Santana, Matheus Lustosa...",Brazil,2019-02-22,2018,TV-PG,2 Seasons,Kids' TV,Fading music biz veteran Zé realizes he has ju...,2019-02-22
4177,s4178,Movie,IO,Jonathan Helpert,"Margaret Qualley, Anthony Mackie, Danny Huston",United States,2019-01-18,2019,TV-14,96 min,"Dramas, Sci-Fi & Fantasy",As a young scientist searches for a way to sav...,2019-01-18
4660,s4661,Movie,PK,Rajkumar Hirani,"Aamir Khan, Anuskha Sharma, Sanjay Dutt, Saura...",India,2018-09-06,2014,TV-14,146 min,"Comedies, Dramas, International Movies",Aamir Khan teams with director Rajkumar Hirani...,2018-09-06
5388,s5389,TV Show,46,Serdar Akar,"Erdal Beşikçioğlu, Yasemin Allen, Melis Birkan...",Turkey,2017-07-01,2016,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Mysteries",A genetics professor experiments with a treatm...,2017-07-01
5958,s5959,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,2017-11-16,2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi...",2017-11-16
5959,s5960,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,2020-01-01,2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020-01-01
7155,s7156,TV Show,K,Unknown,"Daisuke Namikawa, Daisuke Ono, Mikako Komatsu,...",Japan,2016-12-01,2012,TV-MA,1 Season,"Anime Series, Crime TV Shows, International TV...",A young boy is wanted for a crime he has no re...,2016-12-01
7687,s7688,Movie,P,Paul Spurrier,"Suangporn Jaturaphut, Opal, Dor Yodrak, Pisama...","United Kingdom, Thailand",2019-05-31,2006,TV-MA,105 min,"Horror Movies, International Movies",An orphan girl taught magic by her sick grandm...,2019-05-31
8765,s8766,Movie,XX,"Jovanka Vuckovic, Annie Clark, Roxanne Benjami...","Natalie Brown, Jonathan Watton, Melanie Lynske...","Canada, United States",2017-06-22,2017,R,81 min,Horror Movies,This four-part anthology of short horror films...,2017-06-22

Losowe sprawdzenie 20 kolumn

In [240]:
df.sample(20)[["type","title","director","country","rating"]]

,type,title,director,country,rating
1655,Movie,Dragons: Rescue Riders: Huttsgalor Holiday,"Greg Rankin, TJ Sullivan",United States,TV-Y
978,Movie,Deliha,Hakan Algül,Turkey,TV-MA
5943,Movie,Adam: His Song Continues,Robert Markowitz,United States,TV-MA
5780,Movie,Welcome Mr. President,Riccardo Milani,Italy,TV-MA
320,TV Show,Top Secret UFO Projects: Declassified,Unknown,Unknown,TV-PG
2678,Movie,Jem and the Holograms,Jon M. Chu,United States,PG
7996,Movie,Shararat,Gurudev Bhalla,India,TV-PG
2473,TV Show,Dynasty,Unknown,United States,TV-14
3831,TV Show,The Defected,Unknown,"China, Hong Kong",TV-14
1607,Movie,Hazel Brugger: Tropical,Unknown,Germany,TV-MA
5995,Movie,1st Summoning,Raymond Wood,United States,TV-MA
8132,TV Show,Surviving R. Kelly Part II: The Reckoning,Unknown,United States,TV-MA
2241,TV Show,The Business of Drugs,Unknown,United States,TV-MA
2497,Movie,I Will Follow,Ava DuVernay,United States,TV-14
5665,TV Show,Color of Woman,Unknown,South Korea,TV-PG
2161,Movie,Nasha Natasha,Martín Sastre,Uruguay,TV-PG
2869,Movie,Amit Tandon: Family Tandoncies,Unknown,India,TV-14
4854,Movie,Tig Notaro Happy To Be Here,Tig Notaro,United States,TV-14
1990,TV Show,Challenger,Unknown,United States,TV-14
1909,Movie,Free State of Jones,Gary Ross,United States,R

Sprawdzenie ile jest wartosci Unknown w poszczegolnych kolumnach

In [241]:
print("Director:", (df["director"] == "Unknown").sum())
print("Cast:", (df["cast"] == "Unknown").sum())
print("Country:", (df["country"] == "Unknown").sum())

Director: 2624
Cast: 825
Country: 830